Ready for reviewing.
S-Dafarra/inverseKinematics pull request #1
Opened 2017-01-27 09:14 UTC by S-Dafarra

2017-01-27 10:19 UTC, francesco-romano requested changes
Review in inline comments.

2017-01-27 10:19 UTC, francesco-romano commented on CMakeLists.txt
> +endif()
Always put an End of Line at the end of every file.

2017-01-27 10:19 UTC, francesco-romano commented on CMakeLists.txt
> +add_library(${PROJECT_NAME}  SHARED src/InverseKinematicsIPOPT.cpp include/InverseKinematicsIPOPT.h
I (personal taste) tend to create variables with all the headers and sources before and in `add_library` simply call those variables.
While this project is quite ''simple'', with more complex projects you may find yourself with the need to use the list of files more than once.

2017-01-27 10:19 UTC, francesco-romano commented on CMakeLists.txt
> +
Missing the installation part

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    std::vector< std::string > selectedJoints;
be consistent with the spaces. 
In this case I prefer to avoid space between `< >`

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +#endif /* end of include guard: INVERSEKINEMATICS_H */
EOL.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    InverseKinematics();
This is the main (and public) header file of your library.
Remember to always document your code.

Given the other projects in the YARP world, you should use doxygen.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    virtual bool setModel(const iDynTree::Model modelInput);
Pass a reference to the model object to avoid a copy.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    virtual bool prepareProblem(const std::string& filename, const std::vector< std::string >& consideredJoints, const iDynTree::Vector3& gains, const iDynTree::Vector3& desiredPosition, const iDynTr
Maybe it is better to split long lines into multiple lines.
Usually if I have to split a line, I put each parameter on a new line.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    virtual void setDesiredTransformation(const iDynTree::Transform p_H_t);
as before: reference to the object

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +#include <math.h>
use the C++ counterpart of the standard math library, i.e. `#include <cmath>`

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    signed int exitCode;
by default int are signed.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +#include <iDynTree/Core/EigenHelpers.h>
Every include you put in the header file can introduce problems when compiling.
Furthermore they may slow down compilation, or lead to not-needed recompilation.

Everything not necessary should go in the `.cpp`.
Furthermore, start taking a look to the concept of forward declaration

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    virtual bool update();
If you do not need to support hierarchies of classes, `virtual` can lead to slower function calls.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    virtual bool get_nlp_info(Ipopt::Index& n, Ipopt::Index& m, Ipopt::Index& nnz_jac_g,
For better readability add comments so as to separate the section of method needed for IPOpt to the other methods.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +#endif
EOL

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    virtual bool loadFromFile(const std::string &filename, const std::vector< std::string > &consideredJoints);
Side note (given that I still have to read the `.cpp` files.
You can move some of the logic which is not directly tied to IPOpt into the container class, i.e. `InverseKinematics` class, e.g. you can decide to have only the `KinDynComputation` class and leave the initialisation to the other class.

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematics.cpp
> +    loader = IpoptApplicationFactory();
here you are tying the `InverseKinematics` class to `IpOpt` in two ways: by using your IPOpt implementation AND by directly using IpOpt functions. I would confine all IPOpt-related calls in your `InverseKinematicsIPOPT` class

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematics.cpp
> +    success = solverPointer->loadFromFile(filename, consideredJoints);
This is a nice place to return some meaningful error to the user, otherwise he does not understand what is happening. 
Given the not-too-complex library, I would stick to calls to the YARP logger (or directly calling `std::cerr`).

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematics.cpp
> +bool InverseKinematics::setURDF(const std::string& filename, const std::vector< std::string >& consideredJoints)
I would probably simplify the API of your library.
Too many calls to load the URDF. You risk to increase the code complexity the coordinate and managed all the calls.

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    signed int exitCode;
Note that by putting these attributes as public means you are allowing users to modify these values.
Does it make sense that a user modifies the `exitCode` for example?

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +,modelLoaded(false)
be consistent with the use of whitespace characters. I prefer the space between comma and word

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +{
You are calling a method `removeJoints`, but actually I don't understand what you are removing.

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +            consideredJoints.reserve(1);
usually `resize` and `reserve` inside a for loop are symptoms of some problems.

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    const Model input=model;
what is the point of this line?

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        for (std::vector< string >::const_iterator i = consideredJoints.begin(); i != consideredJoints.end(); ++i)
better use `{}`

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        return false;}
endl between `false` and `}`

2017-01-27 10:19 UTC, francesco-romano commented on include/InverseKinematics.h
> +    virtual void setGains(const iDynTree::Vector3& gains);
What do you mean with `gains` ?

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    else if(!framesLoaded){
`else` is not needed here.

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    Eigen::VectorXd X = x_in;
This usually means a copy, i.e. memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    VectorDynSize joints(totalDOF-7);
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        VectorDynSize configuration;
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        MatrixDynSize jacobian;
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    MatrixDynSize e_J_we, p_J_wp;
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    p_J_wp_temp.resize(iKDC.model());
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    e_J_we.resize(6,totalDOF-7);
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +    jacobianOut.resize(6,totalDOF-7);
I think this leads to a memory allocation

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        VectorDynSize x_in(x, totalDOF);
I think the part of 'controlling' the quality of the solution can be left to the calling library.
You have obtained the best solution from the solver. Just "pack" the data and  return to the caller

2017-01-27 10:19 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +int main(){}
??

2017-01-27 10:57 UTC, S-Dafarra commented on include/InverseKinematics.h
> +    virtual void setGains(const iDynTree::Vector3& gains);
Relative gains among position , orientation and "desired joints" parts in the cost function. I need to add documentation.

2017-01-27 10:58 UTC, S-Dafarra commented on include/InverseKinematicsIPOPT.h
> +#include <iDynTree/Core/EigenHelpers.h>
What do you suggest in this case about forward declaration? To what it is referred?

2017-01-27 11:02 UTC, S-Dafarra commented on src/InverseKinematics.cpp
> +    loader = IpoptApplicationFactory();
The point is that an object of ``InverseKinematicsIPOPT`` should be passed to an object of ``IpoptApplicationFactory``, and destroyed after compuations has been made, so how can I do that from the same class? I designed those two classes as a couple for that reason, and unfortunately cannot be easily separable I think.

2017-01-27 11:04 UTC, S-Dafarra commented on src/InverseKinematics.cpp
> +    success = solverPointer->loadFromFile(filename, consideredJoints);
The error is the other class :wink:, which has much more information about models and stuff.

2017-01-27 11:07 UTC, S-Dafarra commented on src/InverseKinematics.cpp
> +bool InverseKinematics::setURDF(const std::string& filename, const std::vector< std::string >& consideredJoints)
I thought that sometimes you just want to consider all joints. Actually those two functions calls the very same method of ``InverseKinematicsIPOPT`` class, just handling the availability of a list of considered joints.

2017-01-27 11:10 UTC, S-Dafarra commented on src/InverseKinematicsIPOPT.cpp
> +{
All joints which has 0 or more than 1 DOF. I did it in order to have a one to one relation between joints and dofs: with 0 DOF joints they are completely useless when computing IK, while for more than one DOF joints, there's no support from ``iDynTree``.

2017-01-27 11:12 UTC, S-Dafarra commented on src/InverseKinematicsIPOPT.cpp
> +            consideredJoints.reserve(1);
Indeed I don't know a priori how many 1dof joints I've in the model.

2017-01-27 11:13 UTC, S-Dafarra commented on src/InverseKinematicsIPOPT.cpp
> +        for (std::vector< string >::const_iterator i = consideredJoints.begin(); i != consideredJoints.end(); ++i)
where? :grin:

2017-01-27 12:13 UTC, francesco-romano commented on include/InverseKinematics.h
> +    virtual void setGains(const iDynTree::Vector3& gains);
weight probably is a more correct term in the optimisation context

2017-01-27 12:34 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +#include <iDynTree/Core/EigenHelpers.h>
Every object whose size is needed at compile time (that is, every object allocated on the stack) must be in "included". All references and pointers can be forward declared. 
All not necessary headers  in the `.h` must be included in the `.cpp` file

2017-01-27 12:35 UTC, francesco-romano commented on src/InverseKinematics.cpp
> +    loader = IpoptApplicationFactory();
You are probably right. 
I am not sure about the memory management needed for IPOpt. I was thinking to something like `Ipopt::SmartPtr<Ipopt::TNLP> xxx(*this);`

2017-01-27 12:35 UTC, francesco-romano commented on src/InverseKinematics.cpp
> +    success = solverPointer->loadFromFile(filename, consideredJoints);
ok. Then the other comment (on the other class) applies.

2017-01-27 12:36 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +            consideredJoints.reserve(1);
then don't use `resize` or `reserve`

2017-01-27 12:37 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +{
still, the name of the function is ambiguous. 
Names are important.

2017-01-27 12:38 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        for (std::vector< string >::const_iterator i = consideredJoints.begin(); i != consideredJoints.end(); ++i)
the `for`. Even if you have only one line in the `for` body, use the brackets.

2017-01-27 12:39 UTC, S-Dafarra commented on src/InverseKinematics.cpp
> +    loader = IpoptApplicationFactory();
Than I think you have a cyclic reference (I'm not really sure is the correct term) which is something to be avoided when using ``Ipopt::SmartPtr`` according to their documentation (if I have understood well).

2017-01-27 13:06 UTC, S-Dafarra commented on src/InverseKinematicsIPOPT.cpp
> +        MatrixDynSize jacobian;
The fact that the declaration is in an ``if`` statement, does it cause problems?

2017-01-27 14:25 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        MatrixDynSize jacobian;
I don't understand the question, sorry. What do you mean with "problem"

2017-01-27 14:28 UTC, S-Dafarra commented on src/InverseKinematicsIPOPT.cpp
> +        MatrixDynSize jacobian;
In the sense that the allocation is done depending on the if statement, thus it is not known at compile whether that variable is allocated or not.

2017-01-27 14:31 UTC, S-Dafarra commented on src/InverseKinematicsIPOPT.cpp
> +{
What do you suggest, given that it is just an internal helper?

2017-01-27 14:31 UTC, francesco-romano commented on src/InverseKinematicsIPOPT.cpp
> +        MatrixDynSize jacobian;
That if is called once with `values == NULL` and all the other times (which varies) with the `values != NULL`, so as you can see you allocate every time but the first one.

2017-02-01 10:17 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    ~InverseKinematicsIPOPT();
Be careful. If you inherit from another class you can no longer choose if methods can be virtual or not

2017-02-01 10:24 UTC, S-Dafarra commented on include/InverseKinematicsIPOPT.h
> +    ~InverseKinematicsIPOPT();
I didn't understand, should it be virtual or not?

2017-02-01 13:28 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    ~InverseKinematicsIPOPT();
If the base class is virtual then yes. If it is not, than no 😛

2017-02-01 13:54 UTC, S-Dafarra commented on include/InverseKinematicsIPOPT.h
> +    ~InverseKinematicsIPOPT();
So in this case I guess yes :grin:. Does it hold for all the inherited methods? What happens if I don't set it as ``virtual``?

2017-02-01 16:52 UTC, francesco-romano commented on include/InverseKinematicsIPOPT.h
> +    ~InverseKinematicsIPOPT();
If I remember correctly you have to put in on the destructor and (or) at least another virtual method. At that point the virtual table should be created. 
But I may be wrong.

2017-02-20 10:37 UTC, merged